// app/layout.tsx or app/layout.jsx
import "./globals.css";
import Nav from "./components/Global/Nav";
import Head from "next/head";
import Footer from "./components/Global/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Head>
        <link href="https://fonts.cdnfonts.com/css/satoshi" rel="stylesheet" />
      </Head>
        <div className="relative bg overflow-y-hidden">
          <Nav />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
